# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-06 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Title')),
                ('link', models.CharField(default='', help_text="Cool URIs don't change", max_length=150, verbose_name='Link')),
                ('snippet', models.CharField(default='', max_length=500, verbose_name='Summary')),
                ('content', models.TextField(verbose_name='Content')),
                ('add_time', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('publish_time', models.DateTimeField(null=True, verbose_name='Issuing Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Change the time')),
                ('status', models.CharField(choices=[('d', 'draft'), ('p', 'release')], default='d', max_length=1, verbose_name='Status')),
                ('is_public', models.BooleanField(default=True, verbose_name='Public')),
                ('is_top', models.BooleanField(default=False, verbose_name='Sticky')),
                ('access_count', models.IntegerField(default=1, editable=False, verbose_name='Pageviews')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Name')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='blog.Tag', verbose_name='Label collection'),
        ),
    ]
